apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  labels:
    io.kompose.service: grafana
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: grafana
  ports:
    - name: "3000" 
      port: 3000
      targetPort: 3000

